// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.33.0
// 	protoc        v4.25.1
// source: agentcomm.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 通用信封，所有消息都封装在此结构中
type Envelope struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Version            string `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`                                                   // "1.0.0"
	Id                 string `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`                                                             // 消息唯一 ID (UUIDv4)
	From               string `protobuf:"bytes,3,opt,name=from,proto3" json:"from,omitempty"`                                                         // 发送方 URN
	To                 string `protobuf:"bytes,4,opt,name=to,proto3" json:"to,omitempty"`                                                             // 接收方 URN
	Type               string `protobuf:"bytes,5,opt,name=type,proto3" json:"type,omitempty"`                                                         // request | notification | ack | task_result | unknown
	Timestamp          int64  `protobuf:"varint,6,opt,name=timestamp,proto3" json:"timestamp,omitempty"`                                              // Unix 秒时间戳
	EphemeralPublicKey []byte `protobuf:"bytes,7,opt,name=ephemeral_public_key,json=ephemeralPublicKey,proto3" json:"ephemeral_public_key,omitempty"` // 临时 X25519 公钥（用于 ECIES）
	Nonce              []byte `protobuf:"bytes,8,opt,name=nonce,proto3" json:"nonce,omitempty"`                                                       // AES-GCM nonce (12 bytes)
	Ciphertext         []byte `protobuf:"bytes,9,opt,name=ciphertext,proto3" json:"ciphertext,omitempty"`                                             // 加密内容
	Tag                []byte `protobuf:"bytes,10,opt,name=tag,proto3" json:"tag,omitempty"`                                                          // GCM 认证标签 (16 bytes)
	Aad                string `protobuf:"bytes,11,opt,name=aad,proto3" json:"aad,omitempty"`                                                          // Additional Auth Data (发送方 fingerprint)
}

func (x *Envelope) Reset() {
	*x = Envelope{}
	if protoimpl.UnsafeEnabled {
		mi := &file_agentcomm_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Envelope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Envelope) ProtoMessage() {}

func (x *Envelope) ProtoReflect() protoreflect.Message {
	mi := &file_agentcomm_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Envelope.ProtoReflect.Descriptor instead.
func (*Envelope) Descriptor() ([]byte, []int) {
	return file_agentcomm_proto_rawDescGZIP(), []int{0}
}

func (x *Envelope) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *Envelope) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Envelope) GetFrom() string {
	if x != nil {
		return x.From
	}
	return ""
}

func (x *Envelope) GetTo() string {
	if x != nil {
		return x.To
	}
	return ""
}

func (x *Envelope) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Envelope) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *Envelope) GetEphemeralPublicKey() []byte {
	if x != nil {
		return x.EphemeralPublicKey
	}
	return nil
}

func (x *Envelope) GetNonce() []byte {
	if x != nil {
		return x.Nonce
	}
	return nil
}

func (x *Envelope) GetCiphertext() []byte {
	if x != nil {
		return x.Ciphertext
	}
	return nil
}

func (x *Envelope) GetTag() []byte {
	if x != nil {
		return x.Tag
	}
	return nil
}

func (x *Envelope) GetAad() string {
	if x != nil {
		return x.Aad
	}
	return ""
}

// Contact JSON 对应的 Protobuf 结构
type Contact struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Version         string   `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`                                          // "1.0"
	Urn             string   `protobuf:"bytes,2,opt,name=urn,proto3" json:"urn,omitempty"`                                                  // URN: urn:hermes:agent:<fingerprint>
	Fingerprint     string   `protobuf:"bytes,3,opt,name=fingerprint,proto3" json:"fingerprint,omitempty"`                                  // Base58(SHA256(Ed25519PubKey))[:16]
	PeerId          string   `protobuf:"bytes,4,opt,name=peer_id,json=peerId,proto3" json:"peer_id,omitempty"`                              // libp2p PeerID (base58 encoded)
	PublicKey       []byte   `protobuf:"bytes,5,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`                     // Ed25519 公钥 (32 bytes)
	X25519PublicKey []byte   `protobuf:"bytes,6,opt,name=x25519_public_key,json=x25519PublicKey,proto3" json:"x25519_public_key,omitempty"` // X25519 公钥 (32 bytes)
	Addrs           []string `protobuf:"bytes,7,rep,name=addrs,proto3" json:"addrs,omitempty"`                                              // 可访问的网络地址列表
	RelayAddrs      []string `protobuf:"bytes,8,rep,name=relay_addrs,json=relayAddrs,proto3" json:"relay_addrs,omitempty"`                  // 中继地址列表
	Signature       []byte   `protobuf:"bytes,9,opt,name=signature,proto3" json:"signature,omitempty"`                                      // Ed25519 签名
	Token           string   `protobuf:"bytes,10,opt,name=token,proto3" json:"token,omitempty"`                                             // 一次性 Token (32 bytes, hex encoded)
	TokenTtl        int64    `protobuf:"varint,11,opt,name=token_ttl,json=tokenTtl,proto3" json:"token_ttl,omitempty"`                      // Token 有效期（秒）
	IssuedAt        int64    `protobuf:"varint,12,opt,name=issued_at,json=issuedAt,proto3" json:"issued_at,omitempty"`                      // 发布时间戳
}

func (x *Contact) Reset() {
	*x = Contact{}
	if protoimpl.UnsafeEnabled {
		mi := &file_agentcomm_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Contact) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Contact) ProtoMessage() {}

func (x *Contact) ProtoReflect() protoreflect.Message {
	mi := &file_agentcomm_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Contact.ProtoReflect.Descriptor instead.
func (*Contact) Descriptor() ([]byte, []int) {
	return file_agentcomm_proto_rawDescGZIP(), []int{1}
}

func (x *Contact) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *Contact) GetUrn() string {
	if x != nil {
		return x.Urn
	}
	return ""
}

func (x *Contact) GetFingerprint() string {
	if x != nil {
		return x.Fingerprint
	}
	return ""
}

func (x *Contact) GetPeerId() string {
	if x != nil {
		return x.PeerId
	}
	return ""
}

func (x *Contact) GetPublicKey() []byte {
	if x != nil {
		return x.PublicKey
	}
	return nil
}

func (x *Contact) GetX25519PublicKey() []byte {
	if x != nil {
		return x.X25519PublicKey
	}
	return nil
}

func (x *Contact) GetAddrs() []string {
	if x != nil {
		return x.Addrs
	}
	return nil
}

func (x *Contact) GetRelayAddrs() []string {
	if x != nil {
		return x.RelayAddrs
	}
	return nil
}

func (x *Contact) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

func (x *Contact) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *Contact) GetTokenTtl() int64 {
	if x != nil {
		return x.TokenTtl
	}
	return 0
}

func (x *Contact) GetIssuedAt() int64 {
	if x != nil {
		return x.IssuedAt
	}
	return 0
}

// 中继节点存储的离线消息元数据
type StoredMessageMeta struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id      string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`                          // 消息 ID
	FromUrn string `protobuf:"bytes,2,opt,name=from_urn,json=fromUrn,proto3" json:"from_urn,omitempty"` // 发送方 URN
	ToUrn   string `protobuf:"bytes,3,opt,name=to_urn,json=toUrn,proto3" json:"to_urn,omitempty"`       // 接收方 URN
	Ts      int64  `protobuf:"varint,4,opt,name=ts,proto3" json:"ts,omitempty"`                         // 发送时间戳
	Ttl     int64  `protobuf:"varint,5,opt,name=ttl,proto3" json:"ttl,omitempty"`                       // 剩余 TTL（秒）
	MsgType string `protobuf:"bytes,6,opt,name=msg_type,json=msgType,proto3" json:"msg_type,omitempty"` // 消息类型
	Iv      []byte `protobuf:"bytes,7,opt,name=iv,proto3" json:"iv,omitempty"`                          // GCM nonce (用于解密校验)
}

func (x *StoredMessageMeta) Reset() {
	*x = StoredMessageMeta{}
	if protoimpl.UnsafeEnabled {
		mi := &file_agentcomm_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StoredMessageMeta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StoredMessageMeta) ProtoMessage() {}

func (x *StoredMessageMeta) ProtoReflect() protoreflect.Message {
	mi := &file_agentcomm_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StoredMessageMeta.ProtoReflect.Descriptor instead.
func (*StoredMessageMeta) Descriptor() ([]byte, []int) {
	return file_agentcomm_proto_rawDescGZIP(), []int{2}
}

func (x *StoredMessageMeta) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *StoredMessageMeta) GetFromUrn() string {
	if x != nil {
		return x.FromUrn
	}
	return ""
}

func (x *StoredMessageMeta) GetToUrn() string {
	if x != nil {
		return x.ToUrn
	}
	return ""
}

func (x *StoredMessageMeta) GetTs() int64 {
	if x != nil {
		return x.Ts
	}
	return 0
}

func (x *StoredMessageMeta) GetTtl() int64 {
	if x != nil {
		return x.Ttl
	}
	return 0
}

func (x *StoredMessageMeta) GetMsgType() string {
	if x != nil {
		return x.MsgType
	}
	return ""
}

func (x *StoredMessageMeta) GetIv() []byte {
	if x != nil {
		return x.Iv
	}
	return nil
}

// 消息列表响应（不返回内容）
type PendingMessages struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Messages []*StoredMessageMeta `protobuf:"bytes,1,rep,name=messages,proto3" json:"messages,omitempty"`
}

func (x *PendingMessages) Reset() {
	*x = PendingMessages{}
	if protoimpl.UnsafeEnabled {
		mi := &file_agentcomm_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PendingMessages) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PendingMessages) ProtoMessage() {}

func (x *PendingMessages) ProtoReflect() protoreflect.Message {
	mi := &file_agentcomm_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PendingMessages.ProtoReflect.Descriptor instead.
func (*PendingMessages) Descriptor() ([]byte, []int) {
	return file_agentcomm_proto_rawDescGZIP(), []int{3}
}

func (x *PendingMessages) GetMessages() []*StoredMessageMeta {
	if x != nil {
		return x.Messages
	}
	return nil
}

// DHT 注册记录
type DHTRecord struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Urn        string   `protobuf:"bytes,1,opt,name=urn,proto3" json:"urn,omitempty"`
	PeerId     string   `protobuf:"bytes,2,opt,name=peer_id,json=peerId,proto3" json:"peer_id,omitempty"`
	Addrs      []string `protobuf:"bytes,3,rep,name=addrs,proto3" json:"addrs,omitempty"`
	RelayAddrs []string `protobuf:"bytes,4,rep,name=relay_addrs,json=relayAddrs,proto3" json:"relay_addrs,omitempty"`
	Ts         int64    `protobuf:"varint,5,opt,name=ts,proto3" json:"ts,omitempty"` // 注册时间戳
}

func (x *DHTRecord) Reset() {
	*x = DHTRecord{}
	if protoimpl.UnsafeEnabled {
		mi := &file_agentcomm_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DHTRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DHTRecord) ProtoMessage() {}

func (x *DHTRecord) ProtoReflect() protoreflect.Message {
	mi := &file_agentcomm_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DHTRecord.ProtoReflect.Descriptor instead.
func (*DHTRecord) Descriptor() ([]byte, []int) {
	return file_agentcomm_proto_rawDescGZIP(), []int{4}
}

func (x *DHTRecord) GetUrn() string {
	if x != nil {
		return x.Urn
	}
	return ""
}

func (x *DHTRecord) GetPeerId() string {
	if x != nil {
		return x.PeerId
	}
	return ""
}

func (x *DHTRecord) GetAddrs() []string {
	if x != nil {
		return x.Addrs
	}
	return nil
}

func (x *DHTRecord) GetRelayAddrs() []string {
	if x != nil {
		return x.RelayAddrs
	}
	return nil
}

func (x *DHTRecord) GetTs() int64 {
	if x != nil {
		return x.Ts
	}
	return 0
}

// WoT 签名记录
type WOTRecord struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SignerUrn  string `protobuf:"bytes,1,opt,name=signer_urn,json=signerUrn,proto3" json:"signer_urn,omitempty"`    // 签名者 URN
	SubjectUrn string `protobuf:"bytes,2,opt,name=subject_urn,json=subjectUrn,proto3" json:"subject_urn,omitempty"` // 被签名者 URN
	TrustLevel string `protobuf:"bytes,3,opt,name=trust_level,json=trustLevel,proto3" json:"trust_level,omitempty"` // high | medium | low
	Signature  []byte `protobuf:"bytes,4,opt,name=signature,proto3" json:"signature,omitempty"`                     // Ed25519 签名
	Ts         int64  `protobuf:"varint,5,opt,name=ts,proto3" json:"ts,omitempty"`                                  // 签名时间戳
}

func (x *WOTRecord) Reset() {
	*x = WOTRecord{}
	if protoimpl.UnsafeEnabled {
		mi := &file_agentcomm_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WOTRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WOTRecord) ProtoMessage() {}

func (x *WOTRecord) ProtoReflect() protoreflect.Message {
	mi := &file_agentcomm_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WOTRecord.ProtoReflect.Descriptor instead.
func (*WOTRecord) Descriptor() ([]byte, []int) {
	return file_agentcomm_proto_rawDescGZIP(), []int{5}
}

func (x *WOTRecord) GetSignerUrn() string {
	if x != nil {
		return x.SignerUrn
	}
	return ""
}

func (x *WOTRecord) GetSubjectUrn() string {
	if x != nil {
		return x.SubjectUrn
	}
	return ""
}

func (x *WOTRecord) GetTrustLevel() string {
	if x != nil {
		return x.TrustLevel
	}
	return ""
}

func (x *WOTRecord) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

func (x *WOTRecord) GetTs() int64 {
	if x != nil {
		return x.Ts
	}
	return 0
}

// libp2p 流处理的请求/响应包装
type StreamMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Payload:
	//
	//	*StreamMessage_Envelope
	//	*StreamMessage_RelayRequest
	//	*StreamMessage_RelayResponse
	Payload isStreamMessage_Payload `protobuf_oneof:"payload"`
}

func (x *StreamMessage) Reset() {
	*x = StreamMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_agentcomm_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StreamMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamMessage) ProtoMessage() {}

func (x *StreamMessage) ProtoReflect() protoreflect.Message {
	mi := &file_agentcomm_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamMessage.ProtoReflect.Descriptor instead.
func (*StreamMessage) Descriptor() ([]byte, []int) {
	return file_agentcomm_proto_rawDescGZIP(), []int{6}
}

func (m *StreamMessage) GetPayload() isStreamMessage_Payload {
	if m != nil {
		return m.Payload
	}
	return nil
}

func (x *StreamMessage) GetEnvelope() *Envelope {
	if x, ok := x.GetPayload().(*StreamMessage_Envelope); ok {
		return x.Envelope
	}
	return nil
}

func (x *StreamMessage) GetRelayRequest() *RelayStoreRequest {
	if x, ok := x.GetPayload().(*StreamMessage_RelayRequest); ok {
		return x.RelayRequest
	}
	return nil
}

func (x *StreamMessage) GetRelayResponse() *RelayStoreResponse {
	if x, ok := x.GetPayload().(*StreamMessage_RelayResponse); ok {
		return x.RelayResponse
	}
	return nil
}

type isStreamMessage_Payload interface {
	isStreamMessage_Payload()
}

type StreamMessage_Envelope struct {
	Envelope *Envelope `protobuf:"bytes,1,opt,name=envelope,proto3,oneof"`
}

type StreamMessage_RelayRequest struct {
	RelayRequest *RelayStoreRequest `protobuf:"bytes,2,opt,name=relay_request,json=relayRequest,proto3,oneof"`
}

type StreamMessage_RelayResponse struct {
	RelayResponse *RelayStoreResponse `protobuf:"bytes,3,opt,name=relay_response,json=relayResponse,proto3,oneof"`
}

func (*StreamMessage_Envelope) isStreamMessage_Payload() {}

func (*StreamMessage_RelayRequest) isStreamMessage_Payload() {}

func (*StreamMessage_RelayResponse) isStreamMessage_Payload() {}

// 中继存储请求
type RelayStoreRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type             string             `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`                                                 // store | list_pending | get_message | ack | revoke
	ToUrn            string             `protobuf:"bytes,2,opt,name=to_urn,json=toUrn,proto3" json:"to_urn,omitempty"`                                  // 目标接收方 URN（用于 list_pending）
	MessageId        string             `protobuf:"bytes,3,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`                      // 消息 ID（用于 get_message / ack）
	EncryptedPayload []byte             `protobuf:"bytes,4,opt,name=encrypted_payload,json=encryptedPayload,proto3" json:"encrypted_payload,omitempty"` // 加密内容（用于 store）
	Meta             *StoredMessageMeta `protobuf:"bytes,5,opt,name=meta,proto3" json:"meta,omitempty"`                                                 // 元数据（用于 store）
}

func (x *RelayStoreRequest) Reset() {
	*x = RelayStoreRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_agentcomm_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RelayStoreRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RelayStoreRequest) ProtoMessage() {}

func (x *RelayStoreRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agentcomm_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RelayStoreRequest.ProtoReflect.Descriptor instead.
func (*RelayStoreRequest) Descriptor() ([]byte, []int) {
	return file_agentcomm_proto_rawDescGZIP(), []int{7}
}

func (x *RelayStoreRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *RelayStoreRequest) GetToUrn() string {
	if x != nil {
		return x.ToUrn
	}
	return ""
}

func (x *RelayStoreRequest) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

func (x *RelayStoreRequest) GetEncryptedPayload() []byte {
	if x != nil {
		return x.EncryptedPayload
	}
	return nil
}

func (x *RelayStoreRequest) GetMeta() *StoredMessageMeta {
	if x != nil {
		return x.Meta
	}
	return nil
}

// 中继存储响应
type RelayStoreResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success          bool                 `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error            string               `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	MessageId        string               `protobuf:"bytes,3,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`                      // 存储成功后返回的 ID
	Pending          []*StoredMessageMeta `protobuf:"bytes,4,rep,name=pending,proto3" json:"pending,omitempty"`                                           // list_pending 返回的列表
	EncryptedPayload []byte               `protobuf:"bytes,5,opt,name=encrypted_payload,json=encryptedPayload,proto3" json:"encrypted_payload,omitempty"` // get_message 返回的加密内容
}

func (x *RelayStoreResponse) Reset() {
	*x = RelayStoreResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_agentcomm_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RelayStoreResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RelayStoreResponse) ProtoMessage() {}

func (x *RelayStoreResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agentcomm_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RelayStoreResponse.ProtoReflect.Descriptor instead.
func (*RelayStoreResponse) Descriptor() ([]byte, []int) {
	return file_agentcomm_proto_rawDescGZIP(), []int{8}
}

func (x *RelayStoreResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *RelayStoreResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *RelayStoreResponse) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

func (x *RelayStoreResponse) GetPending() []*StoredMessageMeta {
	if x != nil {
		return x.Pending
	}
	return nil
}

func (x *RelayStoreResponse) GetEncryptedPayload() []byte {
	if x != nil {
		return x.EncryptedPayload
	}
	return nil
}

var File_agentcomm_proto protoreflect.FileDescriptor

var file_agentcomm_proto_rawDesc = []byte{
	0x0a, 0x0f, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x63, 0x6f, 0x6d, 0x6d, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x09, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x63, 0x6f, 0x6d, 0x6d, 0x22, 0x96, 0x02, 0x0a,
	0x08, 0x45, 0x6e, 0x76, 0x65, 0x6c, 0x6f, 0x70, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x76, 0x65, 0x72,
	0x73, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x76, 0x65, 0x72, 0x73,
	0x69, 0x6f, 0x6e, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x66, 0x72, 0x6f, 0x6d, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x66, 0x72, 0x6f, 0x6d, 0x12, 0x0e, 0x0a, 0x02, 0x74, 0x6f, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x02, 0x74, 0x6f, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18,
	0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x74,
	0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x18, 0x06, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09,
	0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x12, 0x30, 0x0a, 0x14, 0x65, 0x70, 0x68,
	0x65, 0x6d, 0x65, 0x72, 0x61, 0x6c, 0x5f, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x5f, 0x6b, 0x65,
	0x79, 0x18, 0x07, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x12, 0x65, 0x70, 0x68, 0x65, 0x6d, 0x65, 0x72,
	0x61, 0x6c, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x4b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x6e,
	0x6f, 0x6e, 0x63, 0x65, 0x18, 0x08, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x05, 0x6e, 0x6f, 0x6e, 0x63,
	0x65, 0x12, 0x1e, 0x0a, 0x0a, 0x63, 0x69, 0x70, 0x68, 0x65, 0x72, 0x74, 0x65, 0x78, 0x74, 0x18,
	0x09, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x0a, 0x63, 0x69, 0x70, 0x68, 0x65, 0x72, 0x74, 0x65, 0x78,
	0x74, 0x12, 0x10, 0x0a, 0x03, 0x74, 0x61, 0x67, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x03,
	0x74, 0x61, 0x67, 0x12, 0x10, 0x0a, 0x03, 0x61, 0x61, 0x64, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x03, 0x61, 0x61, 0x64, 0x22, 0xe0, 0x02, 0x0a, 0x07, 0x43, 0x6f, 0x6e, 0x74, 0x61, 0x63,
	0x74, 0x12, 0x18, 0x0a, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x10, 0x0a, 0x03, 0x75,
	0x72, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x75, 0x72, 0x6e, 0x12, 0x20, 0x0a,
	0x0b, 0x66, 0x69, 0x6e, 0x67, 0x65, 0x72, 0x70, 0x72, 0x69, 0x6e, 0x74, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0b, 0x66, 0x69, 0x6e, 0x67, 0x65, 0x72, 0x70, 0x72, 0x69, 0x6e, 0x74, 0x12,
	0x17, 0x0a, 0x07, 0x70, 0x65, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x06, 0x70, 0x65, 0x65, 0x72, 0x49, 0x64, 0x12, 0x1d, 0x0a, 0x0a, 0x70, 0x75, 0x62, 0x6c,
	0x69, 0x63, 0x5f, 0x6b, 0x65, 0x79, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x09, 0x70, 0x75,
	0x62, 0x6c, 0x69, 0x63, 0x4b, 0x65, 0x79, 0x12, 0x2a, 0x0a, 0x11, 0x78, 0x32, 0x35, 0x35, 0x31,
	0x39, 0x5f, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x5f, 0x6b, 0x65, 0x79, 0x18, 0x06, 0x20, 0x01,
	0x28, 0x0c, 0x52, 0x0f, 0x78, 0x32, 0x35, 0x35, 0x31, 0x39, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x63,
	0x4b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x61, 0x64, 0x64, 0x72, 0x73, 0x18, 0x07, 0x20, 0x03,
	0x28, 0x09, 0x52, 0x05, 0x61, 0x64, 0x64, 0x72, 0x73, 0x12, 0x1f, 0x0a, 0x0b, 0x72, 0x65, 0x6c,
	0x61, 0x79, 0x5f, 0x61, 0x64, 0x64, 0x72, 0x73, 0x18, 0x08, 0x20, 0x03, 0x28, 0x09, 0x52, 0x0a,
	0x72, 0x65, 0x6c, 0x61, 0x79, 0x41, 0x64, 0x64, 0x72, 0x73, 0x12, 0x1c, 0x0a, 0x09, 0x73, 0x69,
	0x67, 0x6e, 0x61, 0x74, 0x75, 0x72, 0x65, 0x18, 0x09, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x09, 0x73,
	0x69, 0x67, 0x6e, 0x61, 0x74, 0x75, 0x72, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x6b, 0x65,
	0x6e, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x1b,
	0x0a, 0x09, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x5f, 0x74, 0x74, 0x6c, 0x18, 0x0b, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x08, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x54, 0x74, 0x6c, 0x12, 0x1b, 0x0a, 0x09, 0x69,
	0x73, 0x73, 0x75, 0x65, 0x64, 0x5f, 0x61, 0x74, 0x18, 0x0c, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08,
	0x69, 0x73, 0x73, 0x75, 0x65, 0x64, 0x41, 0x74, 0x22, 0xa2, 0x01, 0x0a, 0x11, 0x53, 0x74, 0x6f,
	0x72, 0x65, 0x64, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x4d, 0x65, 0x74, 0x61, 0x12, 0x0e,
	0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x19,
	0x0a, 0x08, 0x66, 0x72, 0x6f, 0x6d, 0x5f, 0x75, 0x72, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x07, 0x66, 0x72, 0x6f, 0x6d, 0x55, 0x72, 0x6e, 0x12, 0x15, 0x0a, 0x06, 0x74, 0x6f, 0x5f,
	0x75, 0x72, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x6f, 0x55, 0x72, 0x6e,
	0x12, 0x0e, 0x0a, 0x02, 0x74, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x74, 0x73,
	0x12, 0x10, 0x0a, 0x03, 0x74, 0x74, 0x6c, 0x18, 0x05, 0x20, 0x01, 0x28, 0x03, 0x52, 0x03, 0x74,
	0x74, 0x6c, 0x12, 0x19, 0x0a, 0x08, 0x6d, 0x73, 0x67, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x06,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x73, 0x67, 0x54, 0x79, 0x70, 0x65, 0x12, 0x0e, 0x0a,
	0x02, 0x69, 0x76, 0x18, 0x07, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x02, 0x69, 0x76, 0x22, 0x4b, 0x0a,
	0x0f, 0x50, 0x65, 0x6e, 0x64, 0x69, 0x6e, 0x67, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73,
	0x12, 0x38, 0x0a, 0x08, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x63, 0x6f, 0x6d, 0x6d, 0x2e, 0x53,
	0x74, 0x6f, 0x72, 0x65, 0x64, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x4d, 0x65, 0x74, 0x61,
	0x52, 0x08, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x22, 0x7d, 0x0a, 0x09, 0x44, 0x48,
	0x54, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x72, 0x6e, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x75, 0x72, 0x6e, 0x12, 0x17, 0x0a, 0x07, 0x70, 0x65, 0x65,
	0x72, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x70, 0x65, 0x65, 0x72,
	0x49, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x61, 0x64, 0x64, 0x72, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28,
	0x09, 0x52, 0x05, 0x61, 0x64, 0x64, 0x72, 0x73, 0x12, 0x1f, 0x0a, 0x0b, 0x72, 0x65, 0x6c, 0x61,
	0x79, 0x5f, 0x61, 0x64, 0x64, 0x72, 0x73, 0x18, 0x04, 0x20, 0x03, 0x28, 0x09, 0x52, 0x0a, 0x72,
	0x65, 0x6c, 0x61, 0x79, 0x41, 0x64, 0x64, 0x72, 0x73, 0x12, 0x0e, 0x0a, 0x02, 0x74, 0x73, 0x18,
	0x05, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x74, 0x73, 0x22, 0x9a, 0x01, 0x0a, 0x09, 0x57, 0x4f,
	0x54, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x12, 0x1d, 0x0a, 0x0a, 0x73, 0x69, 0x67, 0x6e, 0x65,
	0x72, 0x5f, 0x75, 0x72, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x73, 0x69, 0x67,
	0x6e, 0x65, 0x72, 0x55, 0x72, 0x6e, 0x12, 0x1f, 0x0a, 0x0b, 0x73, 0x75, 0x62, 0x6a, 0x65, 0x63,
	0x74, 0x5f, 0x75, 0x72, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x73, 0x75, 0x62,
	0x6a, 0x65, 0x63, 0x74, 0x55, 0x72, 0x6e, 0x12, 0x1f, 0x0a, 0x0b, 0x74, 0x72, 0x75, 0x73, 0x74,
	0x5f, 0x6c, 0x65, 0x76, 0x65, 0x6c, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x74, 0x72,
	0x75, 0x73, 0x74, 0x4c, 0x65, 0x76, 0x65, 0x6c, 0x12, 0x1c, 0x0a, 0x09, 0x73, 0x69, 0x67, 0x6e,
	0x61, 0x74, 0x75, 0x72, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x09, 0x73, 0x69, 0x67,
	0x6e, 0x61, 0x74, 0x75, 0x72, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x74, 0x73, 0x18, 0x05, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x02, 0x74, 0x73, 0x22, 0xda, 0x01, 0x0a, 0x0d, 0x53, 0x74, 0x72, 0x65, 0x61,
	0x6d, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x31, 0x0a, 0x08, 0x65, 0x6e, 0x76, 0x65,
	0x6c, 0x6f, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x61, 0x67, 0x65,
	0x6e, 0x74, 0x63, 0x6f, 0x6d, 0x6d, 0x2e, 0x45, 0x6e, 0x76, 0x65, 0x6c, 0x6f, 0x70, 0x65, 0x48,
	0x00, 0x52, 0x08, 0x65, 0x6e, 0x76, 0x65, 0x6c, 0x6f, 0x70, 0x65, 0x12, 0x43, 0x0a, 0x0d, 0x72,
	0x65, 0x6c, 0x61, 0x79, 0x5f, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x63, 0x6f, 0x6d, 0x6d, 0x2e, 0x52,
	0x65, 0x6c, 0x61, 0x79, 0x53, 0x74, 0x6f, 0x72, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x48, 0x00, 0x52, 0x0c, 0x72, 0x65, 0x6c, 0x61, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x46, 0x0a, 0x0e, 0x72, 0x65, 0x6c, 0x61, 0x79, 0x5f, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1d, 0x2e, 0x61, 0x67, 0x65, 0x6e, 0x74,
	0x63, 0x6f, 0x6d, 0x6d, 0x2e, 0x52, 0x65, 0x6c, 0x61, 0x79, 0x53, 0x74, 0x6f, 0x72, 0x65, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x48, 0x00, 0x52, 0x0d, 0x72, 0x65, 0x6c, 0x61, 0x79,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x09, 0x0a, 0x07, 0x70, 0x61, 0x79, 0x6c,
	0x6f, 0x61, 0x64, 0x22, 0xbc, 0x01, 0x0a, 0x11, 0x52, 0x65, 0x6c, 0x61, 0x79, 0x53, 0x74, 0x6f,
	0x72, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x79, 0x70,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x15, 0x0a,
	0x06, 0x74, 0x6f, 0x5f, 0x75, 0x72, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74,
	0x6f, 0x55, 0x72, 0x6e, 0x12, 0x1d, 0x0a, 0x0a, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x5f,
	0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x49, 0x64, 0x12, 0x2b, 0x0a, 0x11, 0x65, 0x6e, 0x63, 0x72, 0x79, 0x70, 0x74, 0x65, 0x64,
	0x5f, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x10,
	0x65, 0x6e, 0x63, 0x72, 0x79, 0x70, 0x74, 0x65, 0x64, 0x50, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64,
	0x12, 0x30, 0x0a, 0x04, 0x6d, 0x65, 0x74, 0x61, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1c,
	0x2e, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x63, 0x6f, 0x6d, 0x6d, 0x2e, 0x53, 0x74, 0x6f, 0x72, 0x65,
	0x64, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x4d, 0x65, 0x74, 0x61, 0x52, 0x04, 0x6d, 0x65,
	0x74, 0x61, 0x22, 0xc8, 0x01, 0x0a, 0x12, 0x52, 0x65, 0x6c, 0x61, 0x79, 0x53, 0x74, 0x6f, 0x72,
	0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x75, 0x63,
	0x63, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x73, 0x75, 0x63, 0x63,
	0x65, 0x73, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x12, 0x1d, 0x0a, 0x0a, 0x6d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x6d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x49, 0x64, 0x12, 0x36, 0x0a, 0x07, 0x70, 0x65, 0x6e, 0x64,
	0x69, 0x6e, 0x67, 0x18, 0x04, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x61, 0x67, 0x65, 0x6e,
	0x74, 0x63, 0x6f, 0x6d, 0x6d, 0x2e, 0x53, 0x74, 0x6f, 0x72, 0x65, 0x64, 0x4d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x4d, 0x65, 0x74, 0x61, 0x52, 0x07, 0x70, 0x65, 0x6e, 0x64, 0x69, 0x6e, 0x67,
	0x12, 0x2b, 0x0a, 0x11, 0x65, 0x6e, 0x63, 0x72, 0x79, 0x70, 0x74, 0x65, 0x64, 0x5f, 0x70, 0x61,
	0x79, 0x6c, 0x6f, 0x61, 0x64, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x10, 0x65, 0x6e, 0x63,
	0x72, 0x79, 0x70, 0x74, 0x65, 0x64, 0x50, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x42, 0x37, 0x5a,
	0x35, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6e, 0x6f, 0x75, 0x73,
	0x72, 0x65, 0x73, 0x65, 0x61, 0x72, 0x63, 0x68, 0x2f, 0x68, 0x65, 0x72, 0x6d, 0x65, 0x73, 0x2d,
	0x61, 0x67, 0x65, 0x6e, 0x74, 0x2f, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x2d, 0x63, 0x6f, 0x6d, 0x6d,
	0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_agentcomm_proto_rawDescOnce sync.Once
	file_agentcomm_proto_rawDescData = file_agentcomm_proto_rawDesc
)

func file_agentcomm_proto_rawDescGZIP() []byte {
	file_agentcomm_proto_rawDescOnce.Do(func() {
		file_agentcomm_proto_rawDescData = protoimpl.X.CompressGZIP(file_agentcomm_proto_rawDescData)
	})
	return file_agentcomm_proto_rawDescData
}

var file_agentcomm_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_agentcomm_proto_goTypes = []interface{}{
	(*Envelope)(nil),           // 0: agentcomm.Envelope
	(*Contact)(nil),            // 1: agentcomm.Contact
	(*StoredMessageMeta)(nil),  // 2: agentcomm.StoredMessageMeta
	(*PendingMessages)(nil),    // 3: agentcomm.PendingMessages
	(*DHTRecord)(nil),          // 4: agentcomm.DHTRecord
	(*WOTRecord)(nil),          // 5: agentcomm.WOTRecord
	(*StreamMessage)(nil),      // 6: agentcomm.StreamMessage
	(*RelayStoreRequest)(nil),  // 7: agentcomm.RelayStoreRequest
	(*RelayStoreResponse)(nil), // 8: agentcomm.RelayStoreResponse
}
var file_agentcomm_proto_depIdxs = []int32{
	2, // 0: agentcomm.PendingMessages.messages:type_name -> agentcomm.StoredMessageMeta
	0, // 1: agentcomm.StreamMessage.envelope:type_name -> agentcomm.Envelope
	7, // 2: agentcomm.StreamMessage.relay_request:type_name -> agentcomm.RelayStoreRequest
	8, // 3: agentcomm.StreamMessage.relay_response:type_name -> agentcomm.RelayStoreResponse
	2, // 4: agentcomm.RelayStoreRequest.meta:type_name -> agentcomm.StoredMessageMeta
	2, // 5: agentcomm.RelayStoreResponse.pending:type_name -> agentcomm.StoredMessageMeta
	6, // [6:6] is the sub-list for method output_type
	6, // [6:6] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_agentcomm_proto_init() }
func file_agentcomm_proto_init() {
	if File_agentcomm_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_agentcomm_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Envelope); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_agentcomm_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Contact); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_agentcomm_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StoredMessageMeta); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_agentcomm_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PendingMessages); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_agentcomm_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DHTRecord); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_agentcomm_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WOTRecord); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_agentcomm_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StreamMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_agentcomm_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RelayStoreRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_agentcomm_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RelayStoreResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_agentcomm_proto_msgTypes[6].OneofWrappers = []interface{}{
		(*StreamMessage_Envelope)(nil),
		(*StreamMessage_RelayRequest)(nil),
		(*StreamMessage_RelayResponse)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_agentcomm_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_agentcomm_proto_goTypes,
		DependencyIndexes: file_agentcomm_proto_depIdxs,
		MessageInfos:      file_agentcomm_proto_msgTypes,
	}.Build()
	File_agentcomm_proto = out.File
	file_agentcomm_proto_rawDesc = nil
	file_agentcomm_proto_goTypes = nil
	file_agentcomm_proto_depIdxs = nil
}
