// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: proto/envelope.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EncryptedEnvelope struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	SenderUrn           string                 `protobuf:"bytes,1,opt,name=sender_urn,json=senderUrn,proto3" json:"sender_urn,omitempty"`
	SenderStaticPubkey  []byte                 `protobuf:"bytes,2,opt,name=sender_static_pubkey,json=senderStaticPubkey,proto3" json:"sender_static_pubkey,omitempty"`
	EphemeralPubkey     []byte                 `protobuf:"bytes,3,opt,name=ephemeral_pubkey,json=ephemeralPubkey,proto3" json:"ephemeral_pubkey,omitempty"`
	Nonce               []byte                 `protobuf:"bytes,4,opt,name=nonce,proto3" json:"nonce,omitempty"`
	Ciphertext          []byte                 `protobuf:"bytes,5,opt,name=ciphertext,proto3" json:"ciphertext,omitempty"`
	Tag                 []byte                 `protobuf:"bytes,6,opt,name=tag,proto3" json:"tag,omitempty"`
	MessageId           string                 `protobuf:"bytes,7,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	RecipientUrn        string                 `protobuf:"bytes,8,opt,name=recipient_urn,json=recipientUrn,proto3" json:"recipient_urn,omitempty"`
	SenderEd25519Pubkey []byte                 `protobuf:"bytes,9,opt,name=sender_ed25519_pubkey,json=senderEd25519Pubkey,proto3" json:"sender_ed25519_pubkey,omitempty"`
	Signature           []byte                 `protobuf:"bytes,10,opt,name=signature,proto3" json:"signature,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *EncryptedEnvelope) Reset() {
	*x = EncryptedEnvelope{}
	mi := &file_proto_envelope_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EncryptedEnvelope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EncryptedEnvelope) ProtoMessage() {}

func (x *EncryptedEnvelope) ProtoReflect() protoreflect.Message {
	mi := &file_proto_envelope_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EncryptedEnvelope.ProtoReflect.Descriptor instead.
func (*EncryptedEnvelope) Descriptor() ([]byte, []int) {
	return file_proto_envelope_proto_rawDescGZIP(), []int{0}
}

func (x *EncryptedEnvelope) GetSenderUrn() string {
	if x != nil {
		return x.SenderUrn
	}
	return ""
}

func (x *EncryptedEnvelope) GetSenderStaticPubkey() []byte {
	if x != nil {
		return x.SenderStaticPubkey
	}
	return nil
}

func (x *EncryptedEnvelope) GetEphemeralPubkey() []byte {
	if x != nil {
		return x.EphemeralPubkey
	}
	return nil
}

func (x *EncryptedEnvelope) GetNonce() []byte {
	if x != nil {
		return x.Nonce
	}
	return nil
}

func (x *EncryptedEnvelope) GetCiphertext() []byte {
	if x != nil {
		return x.Ciphertext
	}
	return nil
}

func (x *EncryptedEnvelope) GetTag() []byte {
	if x != nil {
		return x.Tag
	}
	return nil
}

func (x *EncryptedEnvelope) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

func (x *EncryptedEnvelope) GetRecipientUrn() string {
	if x != nil {
		return x.RecipientUrn
	}
	return ""
}

func (x *EncryptedEnvelope) GetSenderEd25519Pubkey() []byte {
	if x != nil {
		return x.SenderEd25519Pubkey
	}
	return nil
}

func (x *EncryptedEnvelope) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

type TextMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Text          string                 `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	Timestamp     int64                  `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TextMessage) Reset() {
	*x = TextMessage{}
	mi := &file_proto_envelope_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TextMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TextMessage) ProtoMessage() {}

func (x *TextMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_envelope_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TextMessage.ProtoReflect.Descriptor instead.
func (*TextMessage) Descriptor() ([]byte, []int) {
	return file_proto_envelope_proto_rawDescGZIP(), []int{1}
}

func (x *TextMessage) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *TextMessage) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

type ChatMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Body:
	//
	//	*ChatMessage_Text
	//	*ChatMessage_Raw
	Body          isChatMessage_Body `protobuf_oneof:"body"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatMessage) Reset() {
	*x = ChatMessage{}
	mi := &file_proto_envelope_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatMessage) ProtoMessage() {}

func (x *ChatMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_envelope_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatMessage.ProtoReflect.Descriptor instead.
func (*ChatMessage) Descriptor() ([]byte, []int) {
	return file_proto_envelope_proto_rawDescGZIP(), []int{2}
}

func (x *ChatMessage) GetBody() isChatMessage_Body {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *ChatMessage) GetText() *TextMessage {
	if x != nil {
		if x, ok := x.Body.(*ChatMessage_Text); ok {
			return x.Text
		}
	}
	return nil
}

func (x *ChatMessage) GetRaw() []byte {
	if x != nil {
		if x, ok := x.Body.(*ChatMessage_Raw); ok {
			return x.Raw
		}
	}
	return nil
}

type isChatMessage_Body interface {
	isChatMessage_Body()
}

type ChatMessage_Text struct {
	Text *TextMessage `protobuf:"bytes,1,opt,name=text,proto3,oneof"`
}

type ChatMessage_Raw struct {
	Raw []byte `protobuf:"bytes,99,opt,name=raw,proto3,oneof"`
}

func (*ChatMessage_Text) isChatMessage_Body() {}

func (*ChatMessage_Raw) isChatMessage_Body() {}

var File_proto_envelope_proto protoreflect.FileDescriptor

const file_proto_envelope_proto_rawDesc = "" +
	"\n" +
	"\x14proto/envelope.proto\x12\x05proto\"\xed\x02\n" +
	"\x11EncryptedEnvelope\x12\x1d\n" +
	"\n" +
	"sender_urn\x18\x01 \x01(\tR\tsenderUrn\x120\n" +
	"\x14sender_static_pubkey\x18\x02 \x01(\fR\x12senderStaticPubkey\x12)\n" +
	"\x10ephemeral_pubkey\x18\x03 \x01(\fR\x0fephemeralPubkey\x12\x14\n" +
	"\x05nonce\x18\x04 \x01(\fR\x05nonce\x12\x1e\n" +
	"\n" +
	"ciphertext\x18\x05 \x01(\fR\n" +
	"ciphertext\x12\x10\n" +
	"\x03tag\x18\x06 \x01(\fR\x03tag\x12\x1d\n" +
	"\n" +
	"message_id\x18\a \x01(\tR\tmessageId\x12#\n" +
	"\rrecipient_urn\x18\b \x01(\tR\frecipientUrn\x122\n" +
	"\x15sender_ed25519_pubkey\x18\t \x01(\fR\x13senderEd25519Pubkey\x12\x1c\n" +
	"\tsignature\x18\n" +
	" \x01(\fR\tsignature\"?\n" +
	"\vTextMessage\x12\x12\n" +
	"\x04text\x18\x01 \x01(\tR\x04text\x12\x1c\n" +
	"\ttimestamp\x18\x02 \x01(\x03R\ttimestamp\"S\n" +
	"\vChatMessage\x12(\n" +
	"\x04text\x18\x01 \x01(\v2\x12.proto.TextMessageH\x00R\x04text\x12\x12\n" +
	"\x03raw\x18c \x01(\fH\x00R\x03rawB\x06\n" +
	"\x04bodyB-Z+github.com/BillShiyaoZhang/agent-comm/protob\x06proto3"

var (
	file_proto_envelope_proto_rawDescOnce sync.Once
	file_proto_envelope_proto_rawDescData []byte
)

func file_proto_envelope_proto_rawDescGZIP() []byte {
	file_proto_envelope_proto_rawDescOnce.Do(func() {
		file_proto_envelope_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_envelope_proto_rawDesc), len(file_proto_envelope_proto_rawDesc)))
	})
	return file_proto_envelope_proto_rawDescData
}

var file_proto_envelope_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_proto_envelope_proto_goTypes = []any{
	(*EncryptedEnvelope)(nil), // 0: proto.EncryptedEnvelope
	(*TextMessage)(nil),       // 1: proto.TextMessage
	(*ChatMessage)(nil),       // 2: proto.ChatMessage
}
var file_proto_envelope_proto_depIdxs = []int32{
	1, // 0: proto.ChatMessage.text:type_name -> proto.TextMessage
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_envelope_proto_init() }
func file_proto_envelope_proto_init() {
	if File_proto_envelope_proto != nil {
		return
	}
	file_proto_envelope_proto_msgTypes[2].OneofWrappers = []any{
		(*ChatMessage_Text)(nil),
		(*ChatMessage_Raw)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_envelope_proto_rawDesc), len(file_proto_envelope_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_envelope_proto_goTypes,
		DependencyIndexes: file_proto_envelope_proto_depIdxs,
		MessageInfos:      file_proto_envelope_proto_msgTypes,
	}.Build()
	File_proto_envelope_proto = out.File
	file_proto_envelope_proto_goTypes = nil
	file_proto_envelope_proto_depIdxs = nil
}
