// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: proto/mq.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MQRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Op:
	//
	//	*MQRequest_Store
	//	*MQRequest_Retrieve
	//	*MQRequest_Ack
	Op            isMQRequest_Op `protobuf_oneof:"op"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MQRequest) Reset() {
	*x = MQRequest{}
	mi := &file_proto_mq_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MQRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MQRequest) ProtoMessage() {}

func (x *MQRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mq_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MQRequest.ProtoReflect.Descriptor instead.
func (*MQRequest) Descriptor() ([]byte, []int) {
	return file_proto_mq_proto_rawDescGZIP(), []int{0}
}

func (x *MQRequest) GetOp() isMQRequest_Op {
	if x != nil {
		return x.Op
	}
	return nil
}

func (x *MQRequest) GetStore() *StoreRequest {
	if x != nil {
		if x, ok := x.Op.(*MQRequest_Store); ok {
			return x.Store
		}
	}
	return nil
}

func (x *MQRequest) GetRetrieve() *RetrieveRequest {
	if x != nil {
		if x, ok := x.Op.(*MQRequest_Retrieve); ok {
			return x.Retrieve
		}
	}
	return nil
}

func (x *MQRequest) GetAck() *AckRequest {
	if x != nil {
		if x, ok := x.Op.(*MQRequest_Ack); ok {
			return x.Ack
		}
	}
	return nil
}

type isMQRequest_Op interface {
	isMQRequest_Op()
}

type MQRequest_Store struct {
	Store *StoreRequest `protobuf:"bytes,1,opt,name=store,proto3,oneof"`
}

type MQRequest_Retrieve struct {
	Retrieve *RetrieveRequest `protobuf:"bytes,2,opt,name=retrieve,proto3,oneof"`
}

type MQRequest_Ack struct {
	Ack *AckRequest `protobuf:"bytes,3,opt,name=ack,proto3,oneof"`
}

func (*MQRequest_Store) isMQRequest_Op() {}

func (*MQRequest_Retrieve) isMQRequest_Op() {}

func (*MQRequest_Ack) isMQRequest_Op() {}

type StoreRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RecipientUrn  string                 `protobuf:"bytes,1,opt,name=recipient_urn,json=recipientUrn,proto3" json:"recipient_urn,omitempty"`
	Payload       *EncryptedEnvelope     `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
	ExpiryUnix    int64                  `protobuf:"varint,3,opt,name=expiry_unix,json=expiryUnix,proto3" json:"expiry_unix,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StoreRequest) Reset() {
	*x = StoreRequest{}
	mi := &file_proto_mq_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StoreRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StoreRequest) ProtoMessage() {}

func (x *StoreRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mq_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StoreRequest.ProtoReflect.Descriptor instead.
func (*StoreRequest) Descriptor() ([]byte, []int) {
	return file_proto_mq_proto_rawDescGZIP(), []int{1}
}

func (x *StoreRequest) GetRecipientUrn() string {
	if x != nil {
		return x.RecipientUrn
	}
	return ""
}

func (x *StoreRequest) GetPayload() *EncryptedEnvelope {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *StoreRequest) GetExpiryUnix() int64 {
	if x != nil {
		return x.ExpiryUnix
	}
	return 0
}

type RetrieveRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RecipientUrn  string                 `protobuf:"bytes,1,opt,name=recipient_urn,json=recipientUrn,proto3" json:"recipient_urn,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RetrieveRequest) Reset() {
	*x = RetrieveRequest{}
	mi := &file_proto_mq_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RetrieveRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RetrieveRequest) ProtoMessage() {}

func (x *RetrieveRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mq_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RetrieveRequest.ProtoReflect.Descriptor instead.
func (*RetrieveRequest) Descriptor() ([]byte, []int) {
	return file_proto_mq_proto_rawDescGZIP(), []int{2}
}

func (x *RetrieveRequest) GetRecipientUrn() string {
	if x != nil {
		return x.RecipientUrn
	}
	return ""
}

type AckRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MessageIds    []string               `protobuf:"bytes,1,rep,name=message_ids,json=messageIds,proto3" json:"message_ids,omitempty"`
	RecipientUrn  string                 `protobuf:"bytes,2,opt,name=recipient_urn,json=recipientUrn,proto3" json:"recipient_urn,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AckRequest) Reset() {
	*x = AckRequest{}
	mi := &file_proto_mq_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AckRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AckRequest) ProtoMessage() {}

func (x *AckRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mq_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AckRequest.ProtoReflect.Descriptor instead.
func (*AckRequest) Descriptor() ([]byte, []int) {
	return file_proto_mq_proto_rawDescGZIP(), []int{3}
}

func (x *AckRequest) GetMessageIds() []string {
	if x != nil {
		return x.MessageIds
	}
	return nil
}

func (x *AckRequest) GetRecipientUrn() string {
	if x != nil {
		return x.RecipientUrn
	}
	return ""
}

type MQResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Op:
	//
	//	*MQResponse_Store
	//	*MQResponse_Retrieve
	//	*MQResponse_Ack
	//	*MQResponse_Error
	Op            isMQResponse_Op `protobuf_oneof:"op"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MQResponse) Reset() {
	*x = MQResponse{}
	mi := &file_proto_mq_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MQResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MQResponse) ProtoMessage() {}

func (x *MQResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mq_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MQResponse.ProtoReflect.Descriptor instead.
func (*MQResponse) Descriptor() ([]byte, []int) {
	return file_proto_mq_proto_rawDescGZIP(), []int{4}
}

func (x *MQResponse) GetOp() isMQResponse_Op {
	if x != nil {
		return x.Op
	}
	return nil
}

func (x *MQResponse) GetStore() *StoreResponse {
	if x != nil {
		if x, ok := x.Op.(*MQResponse_Store); ok {
			return x.Store
		}
	}
	return nil
}

func (x *MQResponse) GetRetrieve() *RetrieveResponse {
	if x != nil {
		if x, ok := x.Op.(*MQResponse_Retrieve); ok {
			return x.Retrieve
		}
	}
	return nil
}

func (x *MQResponse) GetAck() *AckResponse {
	if x != nil {
		if x, ok := x.Op.(*MQResponse_Ack); ok {
			return x.Ack
		}
	}
	return nil
}

func (x *MQResponse) GetError() *ErrorResponse {
	if x != nil {
		if x, ok := x.Op.(*MQResponse_Error); ok {
			return x.Error
		}
	}
	return nil
}

type isMQResponse_Op interface {
	isMQResponse_Op()
}

type MQResponse_Store struct {
	Store *StoreResponse `protobuf:"bytes,1,opt,name=store,proto3,oneof"`
}

type MQResponse_Retrieve struct {
	Retrieve *RetrieveResponse `protobuf:"bytes,2,opt,name=retrieve,proto3,oneof"`
}

type MQResponse_Ack struct {
	Ack *AckResponse `protobuf:"bytes,3,opt,name=ack,proto3,oneof"`
}

type MQResponse_Error struct {
	Error *ErrorResponse `protobuf:"bytes,4,opt,name=error,proto3,oneof"`
}

func (*MQResponse_Store) isMQResponse_Op() {}

func (*MQResponse_Retrieve) isMQResponse_Op() {}

func (*MQResponse_Ack) isMQResponse_Op() {}

func (*MQResponse_Error) isMQResponse_Op() {}

type StoreResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	MessageId     string                 `protobuf:"bytes,2,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StoreResponse) Reset() {
	*x = StoreResponse{}
	mi := &file_proto_mq_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StoreResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StoreResponse) ProtoMessage() {}

func (x *StoreResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mq_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StoreResponse.ProtoReflect.Descriptor instead.
func (*StoreResponse) Descriptor() ([]byte, []int) {
	return file_proto_mq_proto_rawDescGZIP(), []int{5}
}

func (x *StoreResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *StoreResponse) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

type RetrieveResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Payloads      []*EncryptedEnvelope   `protobuf:"bytes,1,rep,name=payloads,proto3" json:"payloads,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RetrieveResponse) Reset() {
	*x = RetrieveResponse{}
	mi := &file_proto_mq_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RetrieveResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RetrieveResponse) ProtoMessage() {}

func (x *RetrieveResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mq_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RetrieveResponse.ProtoReflect.Descriptor instead.
func (*RetrieveResponse) Descriptor() ([]byte, []int) {
	return file_proto_mq_proto_rawDescGZIP(), []int{6}
}

func (x *RetrieveResponse) GetPayloads() []*EncryptedEnvelope {
	if x != nil {
		return x.Payloads
	}
	return nil
}

type AckResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	DeletedCount  int32                  `protobuf:"varint,2,opt,name=deleted_count,json=deletedCount,proto3" json:"deleted_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AckResponse) Reset() {
	*x = AckResponse{}
	mi := &file_proto_mq_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AckResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AckResponse) ProtoMessage() {}

func (x *AckResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mq_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AckResponse.ProtoReflect.Descriptor instead.
func (*AckResponse) Descriptor() ([]byte, []int) {
	return file_proto_mq_proto_rawDescGZIP(), []int{7}
}

func (x *AckResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *AckResponse) GetDeletedCount() int32 {
	if x != nil {
		return x.DeletedCount
	}
	return 0
}

type ErrorResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ErrorResponse) Reset() {
	*x = ErrorResponse{}
	mi := &file_proto_mq_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ErrorResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ErrorResponse) ProtoMessage() {}

func (x *ErrorResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mq_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ErrorResponse.ProtoReflect.Descriptor instead.
func (*ErrorResponse) Descriptor() ([]byte, []int) {
	return file_proto_mq_proto_rawDescGZIP(), []int{8}
}

func (x *ErrorResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_proto_mq_proto protoreflect.FileDescriptor

const file_proto_mq_proto_rawDesc = "" +
	"\n" +
	"\x0eproto/mq.proto\x12\x05proto\x1a\x14proto/envelope.proto\"\x9b\x01\n" +
	"\tMQRequest\x12+\n" +
	"\x05store\x18\x01 \x01(\v2\x13.proto.StoreRequestH\x00R\x05store\x124\n" +
	"\bretrieve\x18\x02 \x01(\v2\x16.proto.RetrieveRequestH\x00R\bretrieve\x12%\n" +
	"\x03ack\x18\x03 \x01(\v2\x11.proto.AckRequestH\x00R\x03ackB\x04\n" +
	"\x02op\"\x88\x01\n" +
	"\fStoreRequest\x12#\n" +
	"\rrecipient_urn\x18\x01 \x01(\tR\frecipientUrn\x122\n" +
	"\apayload\x18\x02 \x01(\v2\x18.proto.EncryptedEnvelopeR\apayload\x12\x1f\n" +
	"\vexpiry_unix\x18\x03 \x01(\x03R\n" +
	"expiryUnix\"6\n" +
	"\x0fRetrieveRequest\x12#\n" +
	"\rrecipient_urn\x18\x01 \x01(\tR\frecipientUrn\"R\n" +
	"\n" +
	"AckRequest\x12\x1f\n" +
	"\vmessage_ids\x18\x01 \x03(\tR\n" +
	"messageIds\x12#\n" +
	"\rrecipient_urn\x18\x02 \x01(\tR\frecipientUrn\"\xcd\x01\n" +
	"\n" +
	"MQResponse\x12,\n" +
	"\x05store\x18\x01 \x01(\v2\x14.proto.StoreResponseH\x00R\x05store\x125\n" +
	"\bretrieve\x18\x02 \x01(\v2\x17.proto.RetrieveResponseH\x00R\bretrieve\x12&\n" +
	"\x03ack\x18\x03 \x01(\v2\x12.proto.AckResponseH\x00R\x03ack\x12,\n" +
	"\x05error\x18\x04 \x01(\v2\x14.proto.ErrorResponseH\x00R\x05errorB\x04\n" +
	"\x02op\">\n" +
	"\rStoreResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12\x1d\n" +
	"\n" +
	"message_id\x18\x02 \x01(\tR\tmessageId\"H\n" +
	"\x10RetrieveResponse\x124\n" +
	"\bpayloads\x18\x01 \x03(\v2\x18.proto.EncryptedEnvelopeR\bpayloads\"B\n" +
	"\vAckResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12#\n" +
	"\rdeleted_count\x18\x02 \x01(\x05R\fdeletedCount\")\n" +
	"\rErrorResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessageB-Z+github.com/BillShiyaoZhang/agent-comm/protob\x06proto3"

var (
	file_proto_mq_proto_rawDescOnce sync.Once
	file_proto_mq_proto_rawDescData []byte
)

func file_proto_mq_proto_rawDescGZIP() []byte {
	file_proto_mq_proto_rawDescOnce.Do(func() {
		file_proto_mq_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_mq_proto_rawDesc), len(file_proto_mq_proto_rawDesc)))
	})
	return file_proto_mq_proto_rawDescData
}

var file_proto_mq_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_proto_mq_proto_goTypes = []any{
	(*MQRequest)(nil),         // 0: proto.MQRequest
	(*StoreRequest)(nil),      // 1: proto.StoreRequest
	(*RetrieveRequest)(nil),   // 2: proto.RetrieveRequest
	(*AckRequest)(nil),        // 3: proto.AckRequest
	(*MQResponse)(nil),        // 4: proto.MQResponse
	(*StoreResponse)(nil),     // 5: proto.StoreResponse
	(*RetrieveResponse)(nil),  // 6: proto.RetrieveResponse
	(*AckResponse)(nil),       // 7: proto.AckResponse
	(*ErrorResponse)(nil),     // 8: proto.ErrorResponse
	(*EncryptedEnvelope)(nil), // 9: proto.EncryptedEnvelope
}
var file_proto_mq_proto_depIdxs = []int32{
	1, // 0: proto.MQRequest.store:type_name -> proto.StoreRequest
	2, // 1: proto.MQRequest.retrieve:type_name -> proto.RetrieveRequest
	3, // 2: proto.MQRequest.ack:type_name -> proto.AckRequest
	9, // 3: proto.StoreRequest.payload:type_name -> proto.EncryptedEnvelope
	5, // 4: proto.MQResponse.store:type_name -> proto.StoreResponse
	6, // 5: proto.MQResponse.retrieve:type_name -> proto.RetrieveResponse
	7, // 6: proto.MQResponse.ack:type_name -> proto.AckResponse
	8, // 7: proto.MQResponse.error:type_name -> proto.ErrorResponse
	9, // 8: proto.RetrieveResponse.payloads:type_name -> proto.EncryptedEnvelope
	9, // [9:9] is the sub-list for method output_type
	9, // [9:9] is the sub-list for method input_type
	9, // [9:9] is the sub-list for extension type_name
	9, // [9:9] is the sub-list for extension extendee
	0, // [0:9] is the sub-list for field type_name
}

func init() { file_proto_mq_proto_init() }
func file_proto_mq_proto_init() {
	if File_proto_mq_proto != nil {
		return
	}
	file_proto_envelope_proto_init()
	file_proto_mq_proto_msgTypes[0].OneofWrappers = []any{
		(*MQRequest_Store)(nil),
		(*MQRequest_Retrieve)(nil),
		(*MQRequest_Ack)(nil),
	}
	file_proto_mq_proto_msgTypes[4].OneofWrappers = []any{
		(*MQResponse_Store)(nil),
		(*MQResponse_Retrieve)(nil),
		(*MQResponse_Ack)(nil),
		(*MQResponse_Error)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_mq_proto_rawDesc), len(file_proto_mq_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_mq_proto_goTypes,
		DependencyIndexes: file_proto_mq_proto_depIdxs,
		MessageInfos:      file_proto_mq_proto_msgTypes,
	}.Build()
	File_proto_mq_proto = out.File
	file_proto_mq_proto_goTypes = nil
	file_proto_mq_proto_depIdxs = nil
}
