// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.33.0
// 	protoc        v4.25.1
// source: proto/registry.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type URNRegistryRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Op:
	//
	//	*URNRegistryRequest_Register
	//	*URNRegistryRequest_Resolve
	Op isURNRegistryRequest_Op `protobuf_oneof:"op"`
}

func (x *URNRegistryRequest) Reset() {
	*x = URNRegistryRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_registry_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *URNRegistryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*URNRegistryRequest) ProtoMessage() {}

func (x *URNRegistryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_registry_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use URNRegistryRequest.ProtoReflect.Descriptor instead.
func (*URNRegistryRequest) Descriptor() ([]byte, []int) {
	return file_proto_registry_proto_rawDescGZIP(), []int{0}
}

func (m *URNRegistryRequest) GetOp() isURNRegistryRequest_Op {
	if m != nil {
		return m.Op
	}
	return nil
}

func (x *URNRegistryRequest) GetRegister() *RegisterRequest {
	if x, ok := x.GetOp().(*URNRegistryRequest_Register); ok {
		return x.Register
	}
	return nil
}

func (x *URNRegistryRequest) GetResolve() *ResolveRequest {
	if x, ok := x.GetOp().(*URNRegistryRequest_Resolve); ok {
		return x.Resolve
	}
	return nil
}

type isURNRegistryRequest_Op interface {
	isURNRegistryRequest_Op()
}

type URNRegistryRequest_Register struct {
	Register *RegisterRequest `protobuf:"bytes,1,opt,name=register,proto3,oneof"`
}

type URNRegistryRequest_Resolve struct {
	Resolve *ResolveRequest `protobuf:"bytes,2,opt,name=resolve,proto3,oneof"`
}

func (*URNRegistryRequest_Register) isURNRegistryRequest_Op() {}

func (*URNRegistryRequest_Resolve) isURNRegistryRequest_Op() {}

type RegisterRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Urn          string   `protobuf:"bytes,1,opt,name=urn,proto3" json:"urn,omitempty"`
	PeerId       string   `protobuf:"bytes,2,opt,name=peer_id,json=peerId,proto3" json:"peer_id,omitempty"`
	Addrs        []string `protobuf:"bytes,3,rep,name=addrs,proto3" json:"addrs,omitempty"`
	X25519Pubkey []byte   `protobuf:"bytes,4,opt,name=x25519_pubkey,json=x25519Pubkey,proto3" json:"x25519_pubkey,omitempty"` // X25519 public key for ECIES encryption
}

func (x *RegisterRequest) Reset() {
	*x = RegisterRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_registry_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRequest) ProtoMessage() {}

func (x *RegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_registry_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterRequest.ProtoReflect.Descriptor instead.
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return file_proto_registry_proto_rawDescGZIP(), []int{1}
}

func (x *RegisterRequest) GetUrn() string {
	if x != nil {
		return x.Urn
	}
	return ""
}

func (x *RegisterRequest) GetPeerId() string {
	if x != nil {
		return x.PeerId
	}
	return ""
}

func (x *RegisterRequest) GetAddrs() []string {
	if x != nil {
		return x.Addrs
	}
	return nil
}

func (x *RegisterRequest) GetX25519Pubkey() []byte {
	if x != nil {
		return x.X25519Pubkey
	}
	return nil
}

type ResolveRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Urn string `protobuf:"bytes,1,opt,name=urn,proto3" json:"urn,omitempty"`
}

func (x *ResolveRequest) Reset() {
	*x = ResolveRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_registry_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResolveRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResolveRequest) ProtoMessage() {}

func (x *ResolveRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_registry_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResolveRequest.ProtoReflect.Descriptor instead.
func (*ResolveRequest) Descriptor() ([]byte, []int) {
	return file_proto_registry_proto_rawDescGZIP(), []int{2}
}

func (x *ResolveRequest) GetUrn() string {
	if x != nil {
		return x.Urn
	}
	return ""
}

type URNRegistryResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Op:
	//
	//	*URNRegistryResponse_Register
	//	*URNRegistryResponse_Resolve
	Op isURNRegistryResponse_Op `protobuf_oneof:"op"`
}

func (x *URNRegistryResponse) Reset() {
	*x = URNRegistryResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_registry_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *URNRegistryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*URNRegistryResponse) ProtoMessage() {}

func (x *URNRegistryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_registry_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use URNRegistryResponse.ProtoReflect.Descriptor instead.
func (*URNRegistryResponse) Descriptor() ([]byte, []int) {
	return file_proto_registry_proto_rawDescGZIP(), []int{3}
}

func (m *URNRegistryResponse) GetOp() isURNRegistryResponse_Op {
	if m != nil {
		return m.Op
	}
	return nil
}

func (x *URNRegistryResponse) GetRegister() *RegisterResponse {
	if x, ok := x.GetOp().(*URNRegistryResponse_Register); ok {
		return x.Register
	}
	return nil
}

func (x *URNRegistryResponse) GetResolve() *ResolveResponse {
	if x, ok := x.GetOp().(*URNRegistryResponse_Resolve); ok {
		return x.Resolve
	}
	return nil
}

type isURNRegistryResponse_Op interface {
	isURNRegistryResponse_Op()
}

type URNRegistryResponse_Register struct {
	Register *RegisterResponse `protobuf:"bytes,1,opt,name=register,proto3,oneof"`
}

type URNRegistryResponse_Resolve struct {
	Resolve *ResolveResponse `protobuf:"bytes,2,opt,name=resolve,proto3,oneof"`
}

func (*URNRegistryResponse_Register) isURNRegistryResponse_Op() {}

func (*URNRegistryResponse_Resolve) isURNRegistryResponse_Op() {}

type RegisterResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ok   bool   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	Info string `protobuf:"bytes,2,opt,name=info,proto3" json:"info,omitempty"`
}

func (x *RegisterResponse) Reset() {
	*x = RegisterResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_registry_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RegisterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterResponse) ProtoMessage() {}

func (x *RegisterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_registry_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterResponse.ProtoReflect.Descriptor instead.
func (*RegisterResponse) Descriptor() ([]byte, []int) {
	return file_proto_registry_proto_rawDescGZIP(), []int{4}
}

func (x *RegisterResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *RegisterResponse) GetInfo() string {
	if x != nil {
		return x.Info
	}
	return ""
}

type ResolveResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Found        bool     `protobuf:"varint,1,opt,name=found,proto3" json:"found,omitempty"`
	PeerId       string   `protobuf:"bytes,2,opt,name=peer_id,json=peerId,proto3" json:"peer_id,omitempty"`
	Addrs        []string `protobuf:"bytes,3,rep,name=addrs,proto3" json:"addrs,omitempty"`
	X25519Pubkey []byte   `protobuf:"bytes,4,opt,name=x25519_pubkey,json=x25519Pubkey,proto3" json:"x25519_pubkey,omitempty"` // X25519 public key for ECIES encryption
}

func (x *ResolveResponse) Reset() {
	*x = ResolveResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_registry_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResolveResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResolveResponse) ProtoMessage() {}

func (x *ResolveResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_registry_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResolveResponse.ProtoReflect.Descriptor instead.
func (*ResolveResponse) Descriptor() ([]byte, []int) {
	return file_proto_registry_proto_rawDescGZIP(), []int{5}
}

func (x *ResolveResponse) GetFound() bool {
	if x != nil {
		return x.Found
	}
	return false
}

func (x *ResolveResponse) GetPeerId() string {
	if x != nil {
		return x.PeerId
	}
	return ""
}

func (x *ResolveResponse) GetAddrs() []string {
	if x != nil {
		return x.Addrs
	}
	return nil
}

func (x *ResolveResponse) GetX25519Pubkey() []byte {
	if x != nil {
		return x.X25519Pubkey
	}
	return nil
}

var File_proto_registry_proto protoreflect.FileDescriptor

var file_proto_registry_proto_rawDesc = []byte{
	0x0a, 0x14, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x72, 0x65, 0x67, 0x69, 0x73, 0x74, 0x72, 0x79,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x14, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x65, 0x6e, 0x76, 0x65, 0x6c, 0x6f, 0x70, 0x65, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x22, 0x83, 0x01, 0x0a, 0x12, 0x55, 0x52, 0x4e, 0x52, 0x65, 0x67, 0x69, 0x73,
	0x74, 0x72, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x34, 0x0a, 0x08, 0x72, 0x65,
	0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x48, 0x00, 0x52, 0x08, 0x72, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72,
	0x12, 0x31, 0x0a, 0x07, 0x72, 0x65, 0x73, 0x6f, 0x6c, 0x76, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x15, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x52, 0x65, 0x73, 0x6f, 0x6c, 0x76,
	0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x48, 0x00, 0x52, 0x07, 0x72, 0x65, 0x73, 0x6f,
	0x6c, 0x76, 0x65, 0x42, 0x04, 0x0a, 0x02, 0x6f, 0x70, 0x22, 0x77, 0x0a, 0x0f, 0x52, 0x65, 0x67,
	0x69, 0x73, 0x74, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x10, 0x0a, 0x03,
	0x75, 0x72, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x75, 0x72, 0x6e, 0x12, 0x17,
	0x0a, 0x07, 0x70, 0x65, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x06, 0x70, 0x65, 0x65, 0x72, 0x49, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x61, 0x64, 0x64, 0x72, 0x73,
	0x18, 0x03, 0x20, 0x03, 0x28, 0x09, 0x52, 0x05, 0x61, 0x64, 0x64, 0x72, 0x73, 0x12, 0x23, 0x0a,
	0x0d, 0x78, 0x32, 0x35, 0x35, 0x31, 0x39, 0x5f, 0x70, 0x75, 0x62, 0x6b, 0x65, 0x79, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x0c, 0x52, 0x0c, 0x78, 0x32, 0x35, 0x35, 0x31, 0x39, 0x50, 0x75, 0x62, 0x6b,
	0x65, 0x79, 0x22, 0x22, 0x0a, 0x0e, 0x52, 0x65, 0x73, 0x6f, 0x6c, 0x76, 0x65, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x72, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x03, 0x75, 0x72, 0x6e, 0x22, 0x86, 0x01, 0x0a, 0x13, 0x55, 0x52, 0x4e, 0x52, 0x65,
	0x67, 0x69, 0x73, 0x74, 0x72, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x35,
	0x0a, 0x08, 0x72, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x17, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65,
	0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x48, 0x00, 0x52, 0x08, 0x72, 0x65, 0x67,
	0x69, 0x73, 0x74, 0x65, 0x72, 0x12, 0x32, 0x0a, 0x07, 0x72, 0x65, 0x73, 0x6f, 0x6c, 0x76, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x52,
	0x65, 0x73, 0x6f, 0x6c, 0x76, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x48, 0x00,
	0x52, 0x07, 0x72, 0x65, 0x73, 0x6f, 0x6c, 0x76, 0x65, 0x42, 0x04, 0x0a, 0x02, 0x6f, 0x70, 0x22,
	0x36, 0x0a, 0x10, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x6f, 0x6b, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52,
	0x02, 0x6f, 0x6b, 0x12, 0x12, 0x0a, 0x04, 0x69, 0x6e, 0x66, 0x6f, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x69, 0x6e, 0x66, 0x6f, 0x22, 0x7b, 0x0a, 0x0f, 0x52, 0x65, 0x73, 0x6f, 0x6c,
	0x76, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x66, 0x6f,
	0x75, 0x6e, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x05, 0x66, 0x6f, 0x75, 0x6e, 0x64,
	0x12, 0x17, 0x0a, 0x07, 0x70, 0x65, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x06, 0x70, 0x65, 0x65, 0x72, 0x49, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x61, 0x64, 0x64,
	0x72, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x09, 0x52, 0x05, 0x61, 0x64, 0x64, 0x72, 0x73, 0x12,
	0x23, 0x0a, 0x0d, 0x78, 0x32, 0x35, 0x35, 0x31, 0x39, 0x5f, 0x70, 0x75, 0x62, 0x6b, 0x65, 0x79,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x0c, 0x78, 0x32, 0x35, 0x35, 0x31, 0x39, 0x50, 0x75,
	0x62, 0x6b, 0x65, 0x79, 0x42, 0x37, 0x5a, 0x35, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63,
	0x6f, 0x6d, 0x2f, 0x6e, 0x6f, 0x75, 0x73, 0x72, 0x65, 0x73, 0x65, 0x61, 0x72, 0x63, 0x68, 0x2f,
	0x68, 0x65, 0x72, 0x6d, 0x65, 0x73, 0x2d, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x2f, 0x61, 0x67, 0x65,
	0x6e, 0x74, 0x2d, 0x63, 0x6f, 0x6d, 0x6d, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_registry_proto_rawDescOnce sync.Once
	file_proto_registry_proto_rawDescData = file_proto_registry_proto_rawDesc
)

func file_proto_registry_proto_rawDescGZIP() []byte {
	file_proto_registry_proto_rawDescOnce.Do(func() {
		file_proto_registry_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_registry_proto_rawDescData)
	})
	return file_proto_registry_proto_rawDescData
}

var file_proto_registry_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_proto_registry_proto_goTypes = []interface{}{
	(*URNRegistryRequest)(nil),  // 0: proto.URNRegistryRequest
	(*RegisterRequest)(nil),     // 1: proto.RegisterRequest
	(*ResolveRequest)(nil),      // 2: proto.ResolveRequest
	(*URNRegistryResponse)(nil), // 3: proto.URNRegistryResponse
	(*RegisterResponse)(nil),    // 4: proto.RegisterResponse
	(*ResolveResponse)(nil),     // 5: proto.ResolveResponse
}
var file_proto_registry_proto_depIdxs = []int32{
	1, // 0: proto.URNRegistryRequest.register:type_name -> proto.RegisterRequest
	2, // 1: proto.URNRegistryRequest.resolve:type_name -> proto.ResolveRequest
	4, // 2: proto.URNRegistryResponse.register:type_name -> proto.RegisterResponse
	5, // 3: proto.URNRegistryResponse.resolve:type_name -> proto.ResolveResponse
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_proto_registry_proto_init() }
func file_proto_registry_proto_init() {
	if File_proto_registry_proto != nil {
		return
	}
	file_proto_envelope_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_proto_registry_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*URNRegistryRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_registry_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RegisterRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_registry_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ResolveRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_registry_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*URNRegistryResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_registry_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RegisterResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_registry_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ResolveResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_proto_registry_proto_msgTypes[0].OneofWrappers = []interface{}{
		(*URNRegistryRequest_Register)(nil),
		(*URNRegistryRequest_Resolve)(nil),
	}
	file_proto_registry_proto_msgTypes[3].OneofWrappers = []interface{}{
		(*URNRegistryResponse_Register)(nil),
		(*URNRegistryResponse_Resolve)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_registry_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_registry_proto_goTypes,
		DependencyIndexes: file_proto_registry_proto_depIdxs,
		MessageInfos:      file_proto_registry_proto_msgTypes,
	}.Build()
	File_proto_registry_proto = out.File
	file_proto_registry_proto_rawDesc = nil
	file_proto_registry_proto_goTypes = nil
	file_proto_registry_proto_depIdxs = nil
}
