// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.33.0
// 	protoc        v4.25.1
// source: proto/wot.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TrustLevel int32

const (
	TrustLevel_UNKNOWN   TrustLevel = 0
	TrustLevel_TRUSTED   TrustLevel = 1
	TrustLevel_UNTRUSTED TrustLevel = 2
)

// Enum value maps for TrustLevel.
var (
	TrustLevel_name = map[int32]string{
		0: "UNKNOWN",
		1: "TRUSTED",
		2: "UNTRUSTED",
	}
	TrustLevel_value = map[string]int32{
		"UNKNOWN":   0,
		"TRUSTED":   1,
		"UNTRUSTED": 2,
	}
)

func (x TrustLevel) Enum() *TrustLevel {
	p := new(TrustLevel)
	*p = x
	return p
}

func (x TrustLevel) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TrustLevel) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_wot_proto_enumTypes[0].Descriptor()
}

func (TrustLevel) Type() protoreflect.EnumType {
	return &file_proto_wot_proto_enumTypes[0]
}

func (x TrustLevel) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TrustLevel.Descriptor instead.
func (TrustLevel) EnumDescriptor() ([]byte, []int) {
	return file_proto_wot_proto_rawDescGZIP(), []int{0}
}

// A signed claim that issuer vouches for subject's identity.
// The signature is over SHA256(issuer_urn || subject_urn || subject_peer_id || subject_x25519_pk || level || issued_at).
type TrustClaim struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	IssuerUrn       string     `protobuf:"bytes,1,opt,name=issuer_urn,json=issuerUrn,proto3" json:"issuer_urn,omitempty"`                     // Who made this claim (e.g., "urn:hermes:agent:Charlie")
	SubjectUrn      string     `protobuf:"bytes,2,opt,name=subject_urn,json=subjectUrn,proto3" json:"subject_urn,omitempty"`                  // Who is being claimed about (e.g., "urn:hermes:agent:Alice")
	SubjectPeerId   string     `protobuf:"bytes,3,opt,name=subject_peer_id,json=subjectPeerId,proto3" json:"subject_peer_id,omitempty"`       // Subject's libp2p PeerID (e.g., "12D3KooW...")
	SubjectX25519Pk []byte     `protobuf:"bytes,4,opt,name=subject_x25519_pk,json=subjectX25519Pk,proto3" json:"subject_x25519_pk,omitempty"` // Subject's X25519 static public key (32 bytes)
	Level           TrustLevel `protobuf:"varint,5,opt,name=level,proto3,enum=proto.TrustLevel" json:"level,omitempty"`                       // TRUSTED, UNTRUSTED, or UNKNOWN
	IssuerSignature []byte     `protobuf:"bytes,6,opt,name=issuer_signature,json=issuerSignature,proto3" json:"issuer_signature,omitempty"`   // Ed25519 signature over the claim body
	IssuedAtUnix    int64      `protobuf:"varint,7,opt,name=issued_at_unix,json=issuedAtUnix,proto3" json:"issued_at_unix,omitempty"`         // Unix timestamp
}

func (x *TrustClaim) Reset() {
	*x = TrustClaim{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_wot_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TrustClaim) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrustClaim) ProtoMessage() {}

func (x *TrustClaim) ProtoReflect() protoreflect.Message {
	mi := &file_proto_wot_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrustClaim.ProtoReflect.Descriptor instead.
func (*TrustClaim) Descriptor() ([]byte, []int) {
	return file_proto_wot_proto_rawDescGZIP(), []int{0}
}

func (x *TrustClaim) GetIssuerUrn() string {
	if x != nil {
		return x.IssuerUrn
	}
	return ""
}

func (x *TrustClaim) GetSubjectUrn() string {
	if x != nil {
		return x.SubjectUrn
	}
	return ""
}

func (x *TrustClaim) GetSubjectPeerId() string {
	if x != nil {
		return x.SubjectPeerId
	}
	return ""
}

func (x *TrustClaim) GetSubjectX25519Pk() []byte {
	if x != nil {
		return x.SubjectX25519Pk
	}
	return nil
}

func (x *TrustClaim) GetLevel() TrustLevel {
	if x != nil {
		return x.Level
	}
	return TrustLevel_UNKNOWN
}

func (x *TrustClaim) GetIssuerSignature() []byte {
	if x != nil {
		return x.IssuerSignature
	}
	return nil
}

func (x *TrustClaim) GetIssuedAtUnix() int64 {
	if x != nil {
		return x.IssuedAtUnix
	}
	return 0
}

// WOT operation: query all claims known about a given subject URN.
type WOTQuery struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SubjectUrn string `protobuf:"bytes,1,opt,name=subject_urn,json=subjectUrn,proto3" json:"subject_urn,omitempty"`
}

func (x *WOTQuery) Reset() {
	*x = WOTQuery{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_wot_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WOTQuery) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WOTQuery) ProtoMessage() {}

func (x *WOTQuery) ProtoReflect() protoreflect.Message {
	mi := &file_proto_wot_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WOTQuery.ProtoReflect.Descriptor instead.
func (*WOTQuery) Descriptor() ([]byte, []int) {
	return file_proto_wot_proto_rawDescGZIP(), []int{1}
}

func (x *WOTQuery) GetSubjectUrn() string {
	if x != nil {
		return x.SubjectUrn
	}
	return ""
}

// Response: all claims about the target URN known by this node.
type WOTResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Claims []*TrustClaim `protobuf:"bytes,1,rep,name=claims,proto3" json:"claims,omitempty"`
}

func (x *WOTResponse) Reset() {
	*x = WOTResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_wot_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WOTResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WOTResponse) ProtoMessage() {}

func (x *WOTResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_wot_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WOTResponse.ProtoReflect.Descriptor instead.
func (*WOTResponse) Descriptor() ([]byte, []int) {
	return file_proto_wot_proto_rawDescGZIP(), []int{2}
}

func (x *WOTResponse) GetClaims() []*TrustClaim {
	if x != nil {
		return x.Claims
	}
	return nil
}

// Generic WOT request wrapper.
type WOTRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Op:
	//
	//	*WOTRequest_Query
	Op isWOTRequest_Op `protobuf_oneof:"op"`
}

func (x *WOTRequest) Reset() {
	*x = WOTRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_wot_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WOTRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WOTRequest) ProtoMessage() {}

func (x *WOTRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_wot_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WOTRequest.ProtoReflect.Descriptor instead.
func (*WOTRequest) Descriptor() ([]byte, []int) {
	return file_proto_wot_proto_rawDescGZIP(), []int{3}
}

func (m *WOTRequest) GetOp() isWOTRequest_Op {
	if m != nil {
		return m.Op
	}
	return nil
}

func (x *WOTRequest) GetQuery() *WOTQuery {
	if x, ok := x.GetOp().(*WOTRequest_Query); ok {
		return x.Query
	}
	return nil
}

type isWOTRequest_Op interface {
	isWOTRequest_Op()
}

type WOTRequest_Query struct {
	Query *WOTQuery `protobuf:"bytes,1,opt,name=query,proto3,oneof"` // Future: WOTPublish to gossip claims on the network
}

func (*WOTRequest_Query) isWOTRequest_Op() {}

type WOTResponseWrapper struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Response *WOTResponse `protobuf:"bytes,1,opt,name=response,proto3" json:"response,omitempty"`
}

func (x *WOTResponseWrapper) Reset() {
	*x = WOTResponseWrapper{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_wot_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WOTResponseWrapper) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WOTResponseWrapper) ProtoMessage() {}

func (x *WOTResponseWrapper) ProtoReflect() protoreflect.Message {
	mi := &file_proto_wot_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WOTResponseWrapper.ProtoReflect.Descriptor instead.
func (*WOTResponseWrapper) Descriptor() ([]byte, []int) {
	return file_proto_wot_proto_rawDescGZIP(), []int{4}
}

func (x *WOTResponseWrapper) GetResponse() *WOTResponse {
	if x != nil {
		return x.Response
	}
	return nil
}

var File_proto_wot_proto protoreflect.FileDescriptor

var file_proto_wot_proto_rawDesc = []byte{
	0x0a, 0x0f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x77, 0x6f, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x05, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x9a, 0x02, 0x0a, 0x0a, 0x54, 0x72, 0x75,
	0x73, 0x74, 0x43, 0x6c, 0x61, 0x69, 0x6d, 0x12, 0x1d, 0x0a, 0x0a, 0x69, 0x73, 0x73, 0x75, 0x65,
	0x72, 0x5f, 0x75, 0x72, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x69, 0x73, 0x73,
	0x75, 0x65, 0x72, 0x55, 0x72, 0x6e, 0x12, 0x1f, 0x0a, 0x0b, 0x73, 0x75, 0x62, 0x6a, 0x65, 0x63,
	0x74, 0x5f, 0x75, 0x72, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x73, 0x75, 0x62,
	0x6a, 0x65, 0x63, 0x74, 0x55, 0x72, 0x6e, 0x12, 0x26, 0x0a, 0x0f, 0x73, 0x75, 0x62, 0x6a, 0x65,
	0x63, 0x74, 0x5f, 0x70, 0x65, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0d, 0x73, 0x75, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x50, 0x65, 0x65, 0x72, 0x49, 0x64, 0x12,
	0x2a, 0x0a, 0x11, 0x73, 0x75, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x5f, 0x78, 0x32, 0x35, 0x35, 0x31,
	0x39, 0x5f, 0x70, 0x6b, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x0f, 0x73, 0x75, 0x62, 0x6a,
	0x65, 0x63, 0x74, 0x58, 0x32, 0x35, 0x35, 0x31, 0x39, 0x50, 0x6b, 0x12, 0x27, 0x0a, 0x05, 0x6c,
	0x65, 0x76, 0x65, 0x6c, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x11, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x2e, 0x54, 0x72, 0x75, 0x73, 0x74, 0x4c, 0x65, 0x76, 0x65, 0x6c, 0x52, 0x05, 0x6c,
	0x65, 0x76, 0x65, 0x6c, 0x12, 0x29, 0x0a, 0x10, 0x69, 0x73, 0x73, 0x75, 0x65, 0x72, 0x5f, 0x73,
	0x69, 0x67, 0x6e, 0x61, 0x74, 0x75, 0x72, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x0f,
	0x69, 0x73, 0x73, 0x75, 0x65, 0x72, 0x53, 0x69, 0x67, 0x6e, 0x61, 0x74, 0x75, 0x72, 0x65, 0x12,
	0x24, 0x0a, 0x0e, 0x69, 0x73, 0x73, 0x75, 0x65, 0x64, 0x5f, 0x61, 0x74, 0x5f, 0x75, 0x6e, 0x69,
	0x78, 0x18, 0x07, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0c, 0x69, 0x73, 0x73, 0x75, 0x65, 0x64, 0x41,
	0x74, 0x55, 0x6e, 0x69, 0x78, 0x22, 0x2b, 0x0a, 0x08, 0x57, 0x4f, 0x54, 0x51, 0x75, 0x65, 0x72,
	0x79, 0x12, 0x1f, 0x0a, 0x0b, 0x73, 0x75, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x5f, 0x75, 0x72, 0x6e,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x73, 0x75, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x55,
	0x72, 0x6e, 0x22, 0x38, 0x0a, 0x0b, 0x57, 0x4f, 0x54, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x29, 0x0a, 0x06, 0x63, 0x6c, 0x61, 0x69, 0x6d, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x11, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x54, 0x72, 0x75, 0x73, 0x74, 0x43,
	0x6c, 0x61, 0x69, 0x6d, 0x52, 0x06, 0x63, 0x6c, 0x61, 0x69, 0x6d, 0x73, 0x22, 0x3b, 0x0a, 0x0a,
	0x57, 0x4f, 0x54, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x27, 0x0a, 0x05, 0x71, 0x75,
	0x65, 0x72, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x2e, 0x57, 0x4f, 0x54, 0x51, 0x75, 0x65, 0x72, 0x79, 0x48, 0x00, 0x52, 0x05, 0x71, 0x75,
	0x65, 0x72, 0x79, 0x42, 0x04, 0x0a, 0x02, 0x6f, 0x70, 0x22, 0x44, 0x0a, 0x12, 0x57, 0x4f, 0x54,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x57, 0x72, 0x61, 0x70, 0x70, 0x65, 0x72, 0x12,
	0x2e, 0x0a, 0x08, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x12, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x57, 0x4f, 0x54, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x52, 0x08, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2a,
	0x35, 0x0a, 0x0a, 0x54, 0x72, 0x75, 0x73, 0x74, 0x4c, 0x65, 0x76, 0x65, 0x6c, 0x12, 0x0b, 0x0a,
	0x07, 0x55, 0x4e, 0x4b, 0x4e, 0x4f, 0x57, 0x4e, 0x10, 0x00, 0x12, 0x0b, 0x0a, 0x07, 0x54, 0x52,
	0x55, 0x53, 0x54, 0x45, 0x44, 0x10, 0x01, 0x12, 0x0d, 0x0a, 0x09, 0x55, 0x4e, 0x54, 0x52, 0x55,
	0x53, 0x54, 0x45, 0x44, 0x10, 0x02, 0x42, 0x37, 0x5a, 0x35, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62,
	0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6e, 0x6f, 0x75, 0x73, 0x72, 0x65, 0x73, 0x65, 0x61, 0x72, 0x63,
	0x68, 0x2f, 0x68, 0x65, 0x72, 0x6d, 0x65, 0x73, 0x2d, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x2f, 0x61,
	0x67, 0x65, 0x6e, 0x74, 0x2d, 0x63, 0x6f, 0x6d, 0x6d, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_wot_proto_rawDescOnce sync.Once
	file_proto_wot_proto_rawDescData = file_proto_wot_proto_rawDesc
)

func file_proto_wot_proto_rawDescGZIP() []byte {
	file_proto_wot_proto_rawDescOnce.Do(func() {
		file_proto_wot_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_wot_proto_rawDescData)
	})
	return file_proto_wot_proto_rawDescData
}

var file_proto_wot_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_wot_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_proto_wot_proto_goTypes = []interface{}{
	(TrustLevel)(0),            // 0: proto.TrustLevel
	(*TrustClaim)(nil),         // 1: proto.TrustClaim
	(*WOTQuery)(nil),           // 2: proto.WOTQuery
	(*WOTResponse)(nil),        // 3: proto.WOTResponse
	(*WOTRequest)(nil),         // 4: proto.WOTRequest
	(*WOTResponseWrapper)(nil), // 5: proto.WOTResponseWrapper
}
var file_proto_wot_proto_depIdxs = []int32{
	0, // 0: proto.TrustClaim.level:type_name -> proto.TrustLevel
	1, // 1: proto.WOTResponse.claims:type_name -> proto.TrustClaim
	2, // 2: proto.WOTRequest.query:type_name -> proto.WOTQuery
	3, // 3: proto.WOTResponseWrapper.response:type_name -> proto.WOTResponse
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_proto_wot_proto_init() }
func file_proto_wot_proto_init() {
	if File_proto_wot_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_wot_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TrustClaim); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_wot_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WOTQuery); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_wot_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WOTResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_wot_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WOTRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_wot_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WOTResponseWrapper); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_proto_wot_proto_msgTypes[3].OneofWrappers = []interface{}{
		(*WOTRequest_Query)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_wot_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_wot_proto_goTypes,
		DependencyIndexes: file_proto_wot_proto_depIdxs,
		EnumInfos:         file_proto_wot_proto_enumTypes,
		MessageInfos:      file_proto_wot_proto_msgTypes,
	}.Build()
	File_proto_wot_proto = out.File
	file_proto_wot_proto_rawDesc = nil
	file_proto_wot_proto_goTypes = nil
	file_proto_wot_proto_depIdxs = nil
}
